spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_LOCAL_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    addresses: localhost
    port: 5672
    username: username
    password: password
    virtual-host: /

cloud:
  core-service:
    url: http://localhost:9000
